version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres-db
      - DB_NAME=express_crud
      - DB_PORT=5432
      - DB_PASSWORD=user
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=express_crud
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
